// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAuthenticatedData, GetAuthenticatedErrors, GetAuthenticatedResponses, GetCheckJwtData, GetCheckJwtErrors, GetCheckJwtResponses, GetData, GetHealthData, GetHealthErrors, GetHealthResponses, GetResponses, GetUnauthenticatedData, GetUnauthenticatedResponses, GetUserByAuth0IdData, GetUserByAuth0IdErrors, GetUserByAuth0IdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check endpoint
 *
 * Returns a simple message to confirm the server is running
 */
export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health check endpoint with database connection
 *
 * Checks if the server is running and can connect to the database
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/health',
    ...options
});

/**
 * Get user by Auth0 ID
 *
 * Retrieve a user's information using their Auth0 ID
 */
export const getUserByAuth0Id = <ThrowOnError extends boolean = false>(options: Options<GetUserByAuth0IdData, ThrowOnError>) => (options.client ?? client).get<GetUserByAuth0IdResponses, GetUserByAuth0IdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/user/{auth0Id}',
    ...options
});

/**
 * Verify JWT token
 *
 * Endpoint to verify that the JWT token is valid
 */
export const getCheckJwt = <ThrowOnError extends boolean = false>(options?: Options<GetCheckJwtData, ThrowOnError>) => (options?.client ?? client).get<GetCheckJwtResponses, GetCheckJwtErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/checkJwt',
    ...options
});

/**
 * Unauthenticated test endpoint
 *
 * Public endpoint that doesn't require authentication
 */
export const getUnauthenticated = <ThrowOnError extends boolean = false>(options?: Options<GetUnauthenticatedData, ThrowOnError>) => (options?.client ?? client).get<GetUnauthenticatedResponses, unknown, ThrowOnError>({ url: '/unauthenticated', ...options });

/**
 * Authenticated test endpoint
 *
 * Protected endpoint that requires authentication
 */
export const getAuthenticated = <ThrowOnError extends boolean = false>(options?: Options<GetAuthenticatedData, ThrowOnError>) => (options?.client ?? client).get<GetAuthenticatedResponses, GetAuthenticatedErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/authenticated',
    ...options
});
