// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Application is healthy
     */
    200: {
        status?: string;
        timestamp?: string;
        uptime?: number;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
