// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type User = {
    /**
     * Unique identifier for the user
     */
    id: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User name (optional)
     */
    name?: string | null;
    /**
     * Auth0 identifier for the user
     */
    auth0Id: string;
    /**
     * Timestamp when user was created
     */
    createdAt: string;
    /**
     * Timestamp when user was last updated
     */
    updatedAt: string;
};

export type HealthResponse = {
    status: string;
    message: string;
};

export type HealthErrorResponse = {
    status: string;
    message: string;
    error: string;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * Successful response
     */
    200: {
        message?: string;
    };
};

export type GetResponse = GetResponses[keyof GetResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthErrors = {
    /**
     * Database connection failed
     */
    500: HealthErrorResponse;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * Server and database are healthy
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetUserByAuth0IdData = {
    body?: never;
    path: {
        /**
         * The Auth0 ID of the user
         */
        auth0Id: string;
    };
    query?: never;
    url: '/user/{auth0Id}';
};

export type GetUserByAuth0IdErrors = {
    /**
     * User not found
     */
    404: {
        message?: string;
    };
    /**
     * Internal server error
     */
    500: {
        error?: string;
    };
};

export type GetUserByAuth0IdError = GetUserByAuth0IdErrors[keyof GetUserByAuth0IdErrors];

export type GetUserByAuth0IdResponses = {
    /**
     * User found
     */
    200: User;
};

export type GetUserByAuth0IdResponse = GetUserByAuth0IdResponses[keyof GetUserByAuth0IdResponses];

export type GetCheckJwtData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/checkJwt';
};

export type GetCheckJwtErrors = {
    /**
     * Unauthorized - Invalid or missing token
     */
    401: {
        error?: string;
    };
};

export type GetCheckJwtError = GetCheckJwtErrors[keyof GetCheckJwtErrors];

export type GetCheckJwtResponses = {
    /**
     * Token is valid
     */
    200: {
        message?: string;
        /**
         * The user ID from the token
         */
        userId?: string;
    };
};

export type GetCheckJwtResponse = GetCheckJwtResponses[keyof GetCheckJwtResponses];
